const cartActionTypes = {
  TOGGLE_CART: "TOGGLE_CART",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  CLEAR_FROM_CART: "CLEAR_FROM_CART",
  CLEAR_CART: 'CLEAR_CART'
};

export default cartActionTypes;
